version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    # ports:
    #   - "8002:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - sail

  db:
    image: mysql/mysql-server:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: docker_laravel
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - sail

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
    networks:
      - sail
    ports:
      - 8001:80

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "7000:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - .:/var/www/html
    depends_on:
      - app
    networks:
      - sail

volumes:
  db-data:

networks:
  sail:
    driver: bridge
